[project]
name = "studypy-repl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Annie Giokas", email = "angiokas@pm.me" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
studypy-repl = "studypy_repl:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
