[project]
name = "studypy-core"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Annie Giokas", email = "angiokas@pm.me" }
]
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
