[project]
name = "studypy-tui"
version = "0.1.0"
description = "Package for handling core logic for studypy."
readme = "README.md"
authors = [
    { name = "Annie Giokas", email = "angiokas@pm.me" }
]
requires-python = ">=3.12"
dependencies = [
    "studypy-core",
    "textual>=3.1.0",
    "textual-dev>=1.7.0",
]

[project.scripts]
studypy-tui = "studypy_tui:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
studypy-core = { workspace = true }

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_functions = "test_*"